# wrangler.toml
name = "instagram-bot"
main = "bot.py"
compatibility_date = "2026-06-14"
compatibility_flags = [ "python_workers" ]
disable_python_external_sdk = true  # <--- این خط را اضافه کن تا باگ سیستم بیلد رفع شود

[vars]
BOT_TOKEN = ""
RAPIDAPI_KEY = ""
PROFILE_CHANNEL_ID = ""
POST_CHANNEL_ID = ""
REEL_CHANNEL_ID = ""
STORY_CHANNEL_ID = ""
HIGHLIGHT_CHANNEL_ID = ""
INDEX_CHANNEL_ID = ""

[[kv_namespaces]]
binding = "INDEX_KV"
id = "5ebfdb682065445d88712f8cbe10d93e"

[[queues.producers]]
queue = "instagram-download-queue"
binding = "DOWNLOAD_QUEUE"

[[queues.consumers]]
queue = "instagram-download-queue"
max_batch_size = 1
max_batch_timeout = 1
